#!/bin/sh

# locate this script:
SCRIPT="${BASH_SOURCE[0]}"
if [ -z "$SCRIPT" ]; then
    SCRIPT=$(readlink -f $0)
fi
SCRIPTDIR=$(dirname $SCRIPT)

if ! test -f $SCRIPTDIR/aflplusplus/afl-fuzz; then
    echo "Please run the setup.sh script first."
fi
if ! test -f "$SCRIPTDIR/retrowrite/retro/bin/activate"; then
    echo "Please run the setup.sh script first."
fi


source "$SCRIPTDIR/retrowrite/retro/bin/activate"

# ensure AFL can find itself as well:
export AFL_PATH="$SCRIPTDIR/aflplusplus"

# Add AFL to the path:
export PATH="$SCRIPTDIR/aflplusplus:$PATH"
